### ISSUE TITLE
clearly report when project does not have access to the right keys

### ISSUE THREAD

**Issue by jurgenvinju** [SWAT-engineering/usethesource-deploy-maven-action#1]
This is preventing the release of 0.1.0 of drambiguity:

```
Load key "/home/runner/.ssh/id_ed25519": error in libcrypto
```

See https://github.com/cwi-swat/drambiguity/actions/runs/5964997859/job/16182960721 to read this:

<img width="806" alt="image" src="https://github.com/usethesource/releases-maven-action/assets/1990295/2ac6f43f-d181-4aae-981c-9aede06d928f">

**Comment by jurgenvinju** [comment]
ah.. probably because drambiguity is not in the allowed list in the cwi-swat organization to the secrets. An easier error message would be nice for this.

**Comment by jurgenvinju** [comment]
the `echo ""` was the hint.

**Comment by DavyLandman** [comment]
agreeed, we should throw an error message if certain values are missing
